### PR TITLE
Use https

### PR DESCRIPTION
**Pull request by gwarf**
Default port is 443, so use https protocol.

### CODE REVIEW

**Comment by gwarf** [comment]
So this is now part of #9

**Comment by gwarf** [comment]
Not merged at all in #9 in fact, sorry for the confusion :)
And this is the main fix that will make the nagios checks pass.

**Comment by gwarf** [comment]
I will rebase once #9 will have been merged.

**Comment by bkryza** [comment]
@gwarf Please rebase this branch with master to make sure the Travis checks pass...

**Comment by gwarf** [comment]
Done!

**Pull request merged**
